theme_info:
  name: silverjoke
  description: This theme is created for testing.
  engin: twig

stylesheets:
  all:
   - css/layout.css
   - css/style.css
   - css/colors.css

# Regions
regions:
   header: 'Header'
   help: 'Help'
   page_top: 'Page top'
   page_bottom: 'Page bottom'
   menubar: 'Menu bar'